name: vHive integration tests

on:
  push:
    branches: [ main, legacy-firecracker-v0.24.0-with-upf-support ]
    paths:
    - 'docs/**'
    - '**.md'
    - 'function-images/**'
  pull_request:
    branches: [ main, legacy-firecracker-v0.24.0-with-upf-support ]
    paths:
    - 'docs/**'
    - '**.md'
    - 'function-images/**'
  workflow_dispatch:
  schedule:
    - cron: '0 19 * * 1'

env:
  GOOS: linux
  GO111MODULE: on

jobs:
  integration-tests:
    name: Integration tests
    runs-on: ubuntu-24.04
    steps:
      - run: 'echo "This check not required"'