name: Build and Test OpenYurt Deployer

on:
    push:
      paths:
      - 'docs/**'
      - '**.md'
    pull_request:
      branches: [ main, legacy-firecracker-v0.24.0-with-upf-support ]
      paths:
      - 'docs/**'
      - '**.md'
    workflow_dispatch:

env:
    GOOS: linux
    GO111MODULE: on

jobs:
  openyurt-unit-test:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "This check not required"'
